StockAdmin2/StockAdmin2/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeTemplateView

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('core/', include('core.urls', namespace='core')),
    path('product/', include('product.urls', namespace='product')),
    path('buy/', include('buy.urls', namespace='buy')),
]

StockAdmin2/buy/urls.py
from django.urls import path

from .views import *


app_name = 'buy'
urlpatterns = [
    path('', BuyListView.as_view(), name='buy-list'),
    path('cart/', BuyItemCartFormView.as_view(), name='buy-cart'),
    path('<slug:slug>/', BuyDetailView.as_view(), name='buy-detail'),
    path('update/<slug:slug>/', BuyUpdateView.as_view(), name='buy-update'),
    path('delete/<slug:slug>/', BuyDeleteView.as_view(), name='buy-delete'),
    path('confirm/<slug:slug>/', BuyConfirmView.as_view(), name='buy-confirm'),

    path('stockrecord/stocking/', StockRecordStockingView.as_view(), name='stock-stocking'),
    path('stockrecord/stocked/', stockrecord_stocked_view, name='stock-stocked'),
    path('stockrecord/agg/<slug:type>/', StockRecordAggregateView.as_view(), name='stock-agg'),
    path('buyitem/agg/<slug:type>/', BuyItemAggregateView.as_view(), name='buy-agg'),
    path('buyitem/update-set/', buyitem_update_view, name='buyitem-update-set'),
]

StockAdmin2/product/urls.py
from django.urls import path

from .views import *

app_name = 'product'

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    path('update/<int:pk>/buyinfo/', ProductUpdateBuyInfoCreateView.as_view(), name='update-buyinfo-create'),
    path('update/api/<int:pk>/', api_update, name='api-update'),
]

StockAdmin2/product/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

from .mixins import BuyInfoMixin
from .managers import MarketManager, ProductManager, BuyInfoManager


class Market(models.Model):
    name = models.CharField('도매상명', max_length=50, unique=True)
    tel = models.CharField('전화', max_length=50, blank=True, null=True)
    fax = models.CharField('팩스', max_length=50, blank=True, null=True)
    email = models.EmailField('메일', blank=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = MarketManager()

    class Meta:
        verbose_name = '거래처'
        verbose_name_plural = '거래처'

    def __str__(self):
        return self.name



STD_UNITs = [
    'TAB', 'CAP', 'VIAL', 'AMP', 'BTL', 'EA', 'ML', 'SYR', 'BAG', '포', '통',
    '매', 'PEN', 'G', '관', 'PKG', 'POWD', 'FILM', 'KIT', 'SC', 'GRAN', 'SET',
    'IU', 'PFS', 'SUPP', 'GEL', 'TUBE'
]
ETC_CLASS = '일반', '항암제', '마약', '향정', '수액', '영양수액', '인슐린주사', '백신', '조영제', '처치약품', '소모품', '직송'


class Product(models.Model):
    name = models.CharField('제품명', max_length=50, unique=True)
    code = models.CharField('제품코드', max_length=50, unique=True)
    edi_code = models.CharField('보험코드', max_length=50, blank=True, default="")
    company = models.CharField('판매사', max_length=50, blank=True, default="")
    std_unit = models.CharField('제품규격', max_length=10, choices=zip(STD_UNITs, STD_UNITs), default="")
    pkg_amount = models.IntegerField('포장수량', default=1)
    etc_class = models.CharField('기타구분', max_length=10, choices=zip(ETC_CLASS, ETC_CLASS), default='일반')
    apply_root = models.CharField('복용방법', max_length=50, blank=True, default="")
    unit = models.CharField('적용단위', max_length=50, blank=True, default="")
    unit_amount = models.CharField('규격단위량', max_length=50, blank=True, default="")

    op_type = models.CharField('마약류구분', blank=True, max_length=50, default="")
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProductManager()

    class Meta:
        verbose_name = '제품'
        verbose_name_plural = '제품'
        ordering = '-created',

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:detail', args=(self.pk,))


   
class BuyInfo(BuyInfoMixin, models.Model):
    slug = models.SlugField('구매코드', unique=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    market = models.ForeignKey(Market, on_delete=models.CASCADE, null=True, blank=True)
    buy_edi_code = models.CharField('보험코드', max_length=50, blank=True, default="")
    date = models.DateField('시작일자', blank=True, default=timezone.now)
    price = models.DecimalField('구매가격', max_digits=50, decimal_places=2, default=0)
    pay_type = models.CharField('급여구분', blank=True, max_length=50, default="")
    pro_type = models.CharField('전문/일반', blank=True, max_length=50, default="")
    active = models.BooleanField('사용중', default=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = BuyInfoManager()

    class Meta:
        verbose_name = '구매정보'
        verbose_name_plural = '구매정보'
        ordering = '-created',

    def __str__(self):
        if self.market and self.product:
            title = "{}-{}({:,.0f}원)".format(self.product.name, self.market.name, self.price)
            return title
        return self.slug

StockAdmin2/product/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import Market, Product, BuyInfo


def get_buyinfo_inline_formset(request, instance, **kwargs):
    fields = [
        'product', 'market', 'date', 'price', 'active',
        'pro_type', 'pay_type', 'buy_edi_code'
    ]
    FormSet = inlineformset_factory(Product, BuyInfo, fields=fields, can_delete=True, **kwargs)
    if request.method == "POST":
        return FormSet(request.POST or None, instance=instance)
    return FormSet(instance=instance)

StockAdmin2/product/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.urls import reverse_lazy
from django.views.generic import *

from djangoslicer import SlicePaginatorMixin

from .models import Market, Product, BuyInfo
from .forms import get_buyinfo_inline_formset
from core.filter import QueryFilter
from core.restapi.updater import smart_update



class ProductListView(SlicePaginatorMixin, ListView):
    model = Product
    paginate_by = 25

    def get_queryset(self):
        qs = super(ProductListView, self).get_queryset()
        qf = QueryFilter(self.request, qs)
        return qf.filter_by_search()
        
    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        qf = QueryFilter(self.request)
        context['search_filter_form'] = qf.get_search_filter_form()
        return context
    


class ProductDetailView(DetailView):
    model = Product



class ProductUpdateView(UpdateView):
    model = Product
    fields = [
                'code', 'name', 'company', 'std_unit', 'pkg_amount', 'etc_class', 
                'apply_root', 'unit', 'unit_amount', 'op_type', 'edi_code',
            ]
    formset_extra = 0
    success_url = '.'

    def get_context_data(self, **kwargs):
        context = super(ProductUpdateView, self).get_context_data(**kwargs)
        context['formset']=get_buyinfo_inline_formset(
            self.request, self.get_object(), extra=self.formset_extra
        )
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            formset.save()
        return super(ProductUpdateView, self).form_valid(form)



class ProductUpdateBuyInfoCreateView(ProductUpdateView):
    formset_extra = 1


def api_update(request, pk):
    product = get_object_or_404(Product, pk=pk)
    smart_update(product)
    return redirect(reverse('product:update', args=(pk,)))

StockAdmin2/product/templates/product/product_base.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="col-12 my-3">
    {% block product_header %}{% endblock product_header %}
    </div>
    <div class="row">
    {% block product_content %}{% endblock product_content %}
    </div>
</div>
{% endblock content %}

StockAdmin2/product/templates/product/product_detail.html
{% extends "product/product_base.html" %}

{% block product_header %}
<h4>제품 상세 정보</h4>
<hr>
{% endblock product_header %}
{% block product_content %}
<div class="col-12">

<h5>기본정보</h5>
<table class="product-info tablesorter" border="2">
    <tr>
        <th>제품코드</th>
        <td>{{ object.code }}</td>
        <th>제품명</th>
        <td>{{ object.name }}</td>
        <th>판매사</th>
        <td>{{ object.company }}</td>
    </tr>
    <tr>
        <th>포장수량:</th>
        <td>{{ object.pkg_amount }}</td>
        <th>규격단위:</th>
        <td>{{ object.std_unit }}</td>
        <th>기타구분:</th>
        <td>{{ object.etc_class }}</td>
    </tr>
    <tr>
        <th>적용방법</th>
        <td>{{ object.apply_root }}</td>
        <th>마약류구분</th>
        <td>{{ object.op_type|default:"" }}</td>
        <th>적용단위</th>
        <td>{{ object.unit_amount }} {{ object.unit }}</td>
    </tr>
    <tr>
        <th>보험코드</th>
        <td>{{ object.edi_code }}</td>
    </tr>
</table>
<h5>거래정보</h5>
<table class="product-info tablesorter" border="1">
    <thead>
        <tr>
            <th>거래처</th>
            <th>적용일자</th>
            <th>보험코드</th>
            <th>급여구분</th>
            <th>전문/일반</th>
            <th>거래가격</th>
            <th>사용중</th>
        </tr>
    </thead>
    <tbody>
        {% for info in object.buyinfo_set.all %}
        <tr>
            <td>{{ info.market }}</td>
            <td>{{ info.date|date:"Y-m-d" }}</td>
            <td>{{ info.buy_edi_code }}</td>
            <td>{{ info.pay_type }}</td>
            <td>{{ info.pro_type }}</td>
            <td>{{ info.price }}</td>
            <td>{{ info.active }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
<div class="col-12 text-right">
    <a class="btn btn-info btn-sm" href="{% url 'product:list' %}">목록으로</a>
    <a class="btn btn-warning btn-sm" href="{% url 'product:update' object.pk %}">제품 정보 수정</a>
</div>
{% endblock product_content %}

StockAdmin2/product/templates/product/product_form.html
{% extends "product/product_base.html" %}
{% load widget_tweaks %}

{% block product_header %}
<h4>제품 정보 수정</h4>
<hr>
{% endblock product_header %}
{% block product_content %}

<div class="col-12">
<h5>기본정보</h5>
    <form method="post" action=".">
        {% csrf_token %}     
        <table class="product-info tablesorter" border="2">
            <tr>
                <th>제품코드</th>
                <td>{{ form.code }}</td>
                <th>제품명</th>
                <td>{{ form.name }}</td>
                <th>판매사</th>
                <td>{{ form.company }}</td>
            </tr>
            <tr>
                <th>포장수량:</th>
                <td>{{ form.pkg_amount }}</td>
                <th>규격단위:</th>
                <td>{{ form.std_unit }}</td>
                <th>기타구분:</th>
                <td>{{ form.etc_class }}</td>
            </tr>
            <tr>
                <th>적용방법</th>
                <td>{{ form.apply_root }}</td>
                <th>마약류구분</th>
                <td>{{ form.op_type }}</td>
                <th>적용단위</th>
                <td>{{ form.unit }} {{ form.unit_amount }}</td>
            </tr>
            <tr>
                <th>보험코드</th>
                <td>{{ form.edi_code|attr:"placeholder:자동업데이트 가능하려면 보험코드 필요" }}</td>
                <th>
                    {% if form.instance.edi_code %}
                    <a class="btn btn-warning btn-sm" href="{% url 'product:api-update' object.pk %}" style="height: 25px; padding-top: 1px;">자동업데이트</a>
                    {% else %}
                    <a class="btn btn-secondary btn-sm disabled" href="{% url 'product:api-update' object.pk %}" style="height: 25px; padding-top: 1px;">자동업데이트</a>
                    {% endif %}
                    
                </th>
            </tr>

        </table>

        <h5>거래정보</h5>
        {{ formset.management_form }}
        <table class="product-info tablesorter" border="1">
            <thead>
                <tr>
                    <th>거래처</th>
                    <th>적용일자</th>
                    <th>보험코드</th>
                    <th>급여구분</th>
                    <th>전문/일반</th>
                    <th>거래가격</th>
                    <th>사용중</th>
                    <th>삭제</th>
                </tr>
            </thead>
            <tbody>
                {% for buyinfo_form in formset %}
                    {% for hidden in buyinfo_form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}
                <tr>
                    <td>{{ buyinfo_form.market }}</td>
                    <td>{{ buyinfo_form.date }}</td>
                    <td>{{ buyinfo_form.buy_edi_code }}</td>
                    <td>{{ buyinfo_form.pay_type }}</td>
                    <td>{{ buyinfo_form.pro_type }}</td>
                    <td>{{ buyinfo_form.price }}</td>
                    <td class="text-center">{{ buyinfo_form.active }}</td>
                    {% if buyinfo_form.instance.buyitem_set.exists %}
                    <td class="text-center">삭제불가</td> 
                    {% else %}
                    <th>{{ buyinfo_form.DELETE }}</th>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="col-12 text-right">
            <a class="btn btn-secondary btn-sm" href="{{ form.instance.get_absolute_url }}">돌아가기</a>
            {% if 'buyinfo' not in request.path %}
            <a class="btn btn-warning btn-sm" href="{% url 'product:update-buyinfo-create' form.instance.pk %}">거래정보생성</a>
            {% endif %}
            <button class="btn btn-success btn-sm">저장</button>
        </div>
    </form>
</div>
{% endblock product_content %}

StockAdmin2/product/templates/product/product_list.html
{% extends "product/product_base.html" %}


{% block product_header %}
<h4>제품리스트</h4>
{% endblock product_header %}

{% block product_content %}
<form action=".">
{{ search_filter_form }}
</form>
<table class="tablesorter tablesorter-sortable">
    <thead>
        <tr>
            <th>제품코드</th>
            <th>제품명</th>
            <th>판매사</th>
            <th>포장단위</th>
            <th>구분</th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
        <tr>
            <td>{{ object.code }}</td>
            <td><a href="{{ object.get_absolute_url }}">{{ object.name }}</a></td>
            <td>{{ object.company }}</td>
            <td>{{ object.pkg_amount }}</td>
            <td>{{ object.etc_class }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div class="text-center">
    
{% include "components/paginator.html" %}    
</div>
{% endblock product_content %}