StockAdmin2/StockAdmin2/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeTemplateView

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('core/', include('core.urls', namespace='core')),
    path('product/', include('product.urls', namespace='product')),
    path('buy/', include('buy.urls', namespace='buy')),
]

StockAdmin2/buy/urls.py
from django.urls import path

from .views import *


app_name = 'buy'
urlpatterns = [
    path('', BuyListView.as_view(), name='buy-list'),
    path('cart/', BuyItemCartFormView.as_view(), name='buy-cart'),
    path('<slug:slug>/', BuyDetailView.as_view(), name='buy-detail'),
    path('update/<slug:slug>/', BuyUpdateView.as_view(), name='buy-update'),
    path('delete/<slug:slug>/', BuyDeleteView.as_view(), name='buy-delete'),
    path('confirm/<slug:slug>/', BuyConfirmView.as_view(), name='buy-confirm'),

    path('stockrecord/stocking/', StockRecordStockingView.as_view(), name='stock-stocking'),
    path('stockrecord/stocked/', stockrecord_stocked_view, name='stock-stocked'),
    path('stockrecord/agg/<slug:type>/', StockRecordAggregateView.as_view(), name='stock-agg'),
    path('buyitem/agg/<slug:type>/', BuyItemAggregateView.as_view(), name='buy-agg'),
    path('buyitem/update-set/', buyitem_update_view, name='buyitem-update-set'),
]

StockAdmin2/product/urls.py
from django.urls import path

from .views import *

app_name = 'product'

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    path('update/<int:pk>/buyinfo/', ProductUpdateBuyInfoCreateView.as_view(), name='update-buyinfo-create'),
    path('update/api/<int:pk>/', api_update, name='api-update'),
]

StockAdmin2/buy/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import *
from django.urls import reverse
from django.utils import timezone

from .managers import StockRecordManager, BuyItemManager

from utils.shortcuts import sequence_date_slugify



class Buy(models.Model):
    slug = models.SlugField('구매번호', unique=True, blank=True, editable=False)
    commiter = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL)
    date = models.DateField('구매일자', blank=True, default=timezone.now)
    iscart = models.BooleanField('카트인지', blank=True, default=False)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = '구매요청서'
        verbose_name_plural = '구매요청서'
        ordering = '-created', 

    def __str__(self):
        return self.slug

    def save(self, **kwargs):
        if not self.slug:
            self.slug = sequence_date_slugify(self, 'date')
        return super(Buy, self).save(**kwargs)

    def get_absolute_url(self):
        return reverse('buy:buy-detail', args=(self.slug,))

    @property
    def description(self):
        itemset = self.buyitem_set.all()
        if itemset.exists():
            fistitem = str(itemset.first().buyinfo)
            count = itemset.count()
            return "{} 등 {}건".format(fistitem, count)
        return "내역없음"

    def get_complete_rate(self):
        total_buyitem_count = self.buyitem_set.count()
        if total_buyitem_count > 0:
            annoset = self.buyitem_set.annotate(stocked_amount_sum=Sum('stockrecord__amount'))
            completed_set = annoset.filter(Q(stocked_amount_sum=F('amount'))|Q(isend=True) )
            return completed_set.count() / total_buyitem_count
        return 0

    def has_stockset(self):
        return StockRecord.objects.filter(amount__gt=0, buyitem__buy=self).exists()

    def get_total_price_sum(self):
        annoset, total_price = self.buyitem_set.all().group_by_fk(only_valid=False)
        return total_price


class BuyItem(models.Model):
    buy = models.ForeignKey(Buy, null=True, blank=True, on_delete=models.CASCADE)
    buyinfo = models.ForeignKey('product.BuyInfo', on_delete=models.PROTECT)
    amount = models.IntegerField('구매수량')
    comment = models.CharField('비고', max_length=50, blank=True)
    isend = models.BooleanField('구매종결', default=False)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = BuyItemManager()

    class Meta:
        verbose_name = '구매품목'
        verbose_name_plural = '구매품목'
        unique_together = 'buy', 'buyinfo',

    def __init__(self, *args, **kwargs):
        super(BuyItem, self).__init__(*args, **kwargs)

    def __str__(self):
        return str(self.buyinfo)

    def save(self, **kwargs):
        super(BuyItem, self).save(**kwargs)
        self.reload_zero_stockrecord()          

    def get_stocked_sum(self):
        aggset = self.stockrecord_set.aggregate(stocked=Sum('amount'))
        return aggset['stocked'] or 0

    def get_incompleted_stock(self):
        return self.amount - self.get_stocked_sum()

    def get_incompleted_stock_by_pkg(self):
        incompleted_stock = self.get_incompleted_stock()
        pkg_amount = self.buyinfo.product.pkg_amount or 1
        return incompleted_stock//pkg_amount

    @property
    def stocked_percent(self):
        return self.get_stocked_sum()*100/self.amount

    @property
    def ended_percent(self):
        if self.isend:
            return 100 - self.stocked_percent
        return 0

    def get_stock_status(self):
        if self.isend == True:
            return '종결'
        elif self.get_incompleted_stock() == 0:
            return '완료'
        else:
            return '입고중'

    def get_buy_price(self):
        price = self.buyinfo.price or 0
        return self.amount * price

    @property
    def iscompleted(self):
        return self.get_stock_status() in ['완료', '종결']

    def reload_zero_stockrecord(self):
        zeroset = self.stockrecord_set.filter(amount=0)

        if self.iscompleted:
            if zeroset.exists():
                zeroset.delete()
        else:
            if zeroset.exists():
                if zeroset.count() > 1:
                    zeroset.delete()
                    self.stockrecord_set.create()
            else:
                self.stockrecord_set.create()



class StockRecord(models.Model):
    buyitem = models.ForeignKey(BuyItem, on_delete=models.CASCADE)
    date = models.DateField('입고일자', blank=True, null=True)
    amount = models.IntegerField('입고수량', default=0)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = StockRecordManager()

    class Meta:
        verbose_name_plural = '입고기록'
        verbose_name = '입고기록'
        ordering = '-buyitem__created',

    def __init__(self, *args, **kwargs):
        super(StockRecord, self).__init__(*args, **kwargs)
        self.old_amount  = self.amount
        
    def __str__(self):
        return str(self.buyitem)

    def save(self, **kwargs):
        super(StockRecord, self).save(**kwargs)
        self.buyitem.reload_zero_stockrecord()

    def delete(self):
        buyitem = self.buyitem
        super(StockRecord, self).delete()
        buyitem.reload_zero_stockrecord()

    def clean(self):
        stockrecord_set = self.buyitem.stockrecord_set
        if self.id:
            stocked_amount = self.buyitem.get_stocked_sum()
            new_amount = stocked_amount - self.old_amount + self.amount
            if new_amount > self.buyitem.amount:
                raise ValidationError('입고수량이 구매수량을 초과 합니다')

StockAdmin2/product/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

from .mixins import BuyInfoMixin
from .managers import MarketManager, ProductManager, BuyInfoManager


class Market(models.Model):
    name = models.CharField('도매상명', max_length=50, unique=True)
    tel = models.CharField('전화', max_length=50, blank=True, null=True)
    fax = models.CharField('팩스', max_length=50, blank=True, null=True)
    email = models.EmailField('메일', blank=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = MarketManager()

    class Meta:
        verbose_name = '거래처'
        verbose_name_plural = '거래처'

    def __str__(self):
        return self.name



STD_UNITs = [
    'TAB', 'CAP', 'VIAL', 'AMP', 'BTL', 'EA', 'ML', 'SYR', 'BAG', '포', '통',
    '매', 'PEN', 'G', '관', 'PKG', 'POWD', 'FILM', 'KIT', 'SC', 'GRAN', 'SET',
    'IU', 'PFS', 'SUPP', 'GEL', 'TUBE'
]
ETC_CLASS = '일반', '항암제', '마약', '향정', '수액', '영양수액', '인슐린주사', '백신', '조영제', '처치약품', '소모품', '직송'


class Product(models.Model):
    name = models.CharField('제품명', max_length=50, unique=True)
    code = models.CharField('제품코드', max_length=50, unique=True)
    edi_code = models.CharField('보험코드', max_length=50, blank=True, default="")
    company = models.CharField('판매사', max_length=50, blank=True, default="")
    std_unit = models.CharField('제품규격', max_length=10, choices=zip(STD_UNITs, STD_UNITs), default="")
    pkg_amount = models.IntegerField('포장수량', default=1)
    etc_class = models.CharField('기타구분', max_length=10, choices=zip(ETC_CLASS, ETC_CLASS), default='일반')
    apply_root = models.CharField('복용방법', max_length=50, blank=True, default="")
    unit = models.CharField('적용단위', max_length=50, blank=True, default="")
    unit_amount = models.CharField('규격단위량', max_length=50, blank=True, default="")

    op_type = models.CharField('마약류구분', blank=True, max_length=50, default="")
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProductManager()

    class Meta:
        verbose_name = '제품'
        verbose_name_plural = '제품'
        ordering = '-created',

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:detail', args=(self.pk,))


   
class BuyInfo(BuyInfoMixin, models.Model):
    slug = models.SlugField('구매코드', unique=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    market = models.ForeignKey(Market, on_delete=models.CASCADE, null=True, blank=True)
    buy_edi_code = models.CharField('보험코드', max_length=50, blank=True, default="")
    date = models.DateField('시작일자', blank=True, default=timezone.now)
    price = models.DecimalField('구매가격', max_digits=50, decimal_places=2, default=0)
    pay_type = models.CharField('급여구분', blank=True, max_length=50, default="")
    pro_type = models.CharField('전문/일반', blank=True, max_length=50, default="")
    active = models.BooleanField('사용중', default=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = BuyInfoManager()

    class Meta:
        verbose_name = '구매정보'
        verbose_name_plural = '구매정보'
        ordering = '-created',

    def __str__(self):
        if self.market and self.product:
            title = "{}-{}({:,.0f}원)".format(self.product.name, self.market.name, self.price)
            return title
        return self.slug

StockAdmin2/templates/components/delete_confirm_button.html
<!-- Button trigger modal -->
<button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#{{ modal_id }}">
  {{ button_name|default:"삭제" }}
</button>

<div class="modal fade" id="{{ modal_id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">삭제확인</h5>
      </div>
      <div class="modal-body text-center">
        {{ confirm_message|default:"정말로 삭제 하시겠습니까?" }}
      </div>
      <div class="modal-footer">
        <form method="post" action="{{ action }}">
          {% csrf_token %}
          <button type="submit" class="btn btn-primary btn-sm">삭제</button>
          <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">취소</button>
        </form>
      </div>
    </div>
  </div>
</div>

StockAdmin2/templates/components/navbar.html
{% url 'product:list' as product_list %}
{% url 'buy:buy-list' as buy_list %}

<style type="text/css">
	.dropdown-submenu {
  position: relative;
}

.dropdown-submenu a::after {
  transform: rotate(-90deg);
  position: absolute;
  right: 6px;
  top: .8em;
}

.dropdown-submenu .dropdown-menu {
  top: 0;
  left: 100%;
  margin-left: .1rem;
  margin-right: .1rem;
}
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarTogglerDemo01">
		    <a class="navbar-brand" href="/">StockAdmin2</a>
		    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle {% if product_list in request.path %}active{% endif %}" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					제품정보
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
					<a class="dropdown-item" href="{{ product_list }}">제품목록</a>
					<a class="dropdown-item" href="#">메뉴2</a>
					<a class="dropdown-item" href="#">메뉴3</a>
					</div>
				</li>
		   		<li class="nav-item dropdown">
			        <a class="nav-link dropdown-toggle {% if buy_list in request.path %}active{% endif %}" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			          구매/입고
			        </a>
			        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
			          <li class="dropdown-submenu">
			          	<a class="dropdown-item dropdown-toggle" href="#">구매</a>
			            <ul class="dropdown-menu">
			              <li><a class="dropdown-item" href="{% url 'buy:buy-cart' %}">구매품목입력</a></li>
                          <li><a class="dropdown-item" href="{{ buy_list }}">구매요청서목록</a></li>
			              <li><a class="dropdown-item" href="{% url 'buy:buy-agg' 'BuyItem' %}">구매내역</a></li>
			            </ul>
			          </li>
			          <li class="dropdown-submenu">
			          	<a class="dropdown-item dropdown-toggle" href="#">입고</a>
			            <ul class="dropdown-menu">
			              <li><a class="dropdown-item" href="{% url 'buy:stock-stocking' %}">입고잡기</a></li>
			              <li><a class="dropdown-item" href="{% url 'buy:stock-agg' 'StockRecord' %}">입고내역</a></li>
			            </ul>
			          </li>
			        </ul>
				</li>
		    </ul>
		    <form class="form-inline my-2 my-lg-0">
		      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
		      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
		    </form>
		</div>
	</div>
</nav>
<script type="text/javascript">
	$('.dropdown-menu a.dropdown-toggle').on('click', function(e) {
  if (!$(this).next().hasClass('show')) {
    $(this).parents('.dropdown-menu').first().find('.show').removeClass("show");
  }
  var $subMenu = $(this).next(".dropdown-menu");
  $subMenu.toggleClass('show');


  $(this).parents('li.nav-item.dropdown.show').on('hidden.bs.dropdown', function(e) {
    $('.dropdown-submenu .show').removeClass("show");
  });
  return false;
});
</script>

StockAdmin2/templates/components/paginator.html
<div aria-label="Page navigation example" style="text-align: center">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            {% if request.path %}
            <li class="page-item"><a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">이전 페이지</a></li>
            {% else %}
            <li class="pagn-item disabled"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">이전 페이지</a></li> 
            {% endif %}
        {% else %}
            {% if request.path %}
            <li class="page-item"><a class="page-link" href="{{ request.path }}?page=1" disabled="disabled">이전 페이지</a></li>
            {% else %}  
            <li class="page-item"><a class="page-link" href="?page=1" disabled="disabled">이전 페이지</a></li>
            {% endif %}
        {% endif %} 
        {% for i in page_obj.paginator.page_range %} 
            {% if page_obj.has_next %}
                {% if request.path %}
                <li class="page-item" {% if i == page_obj.number %}class="active"{% endif %}><a class="page-link" href="{{ request.path }}?page={{i}}">{{i}}</a></li>
                {% else %}
                <li class="page-item" {% if i == page_obj.number %}class="active"{% endif %}><a class="page-link" href="?page={{i}}">{{i}}</a></li> 
                {% endif %}
            {% endif %} 
        {% endfor %} 
        {% if page_obj.has_next %}
            {% if request.path %}
            <li class="page-item"><a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">다음페이지</a></li>   
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">다음페이지</a></li>  
            {% endif %}
        {% else %}
            {% if request.path %}
            <li class="page-item"><a class="page-link" href="{{ request.get_full_path }}?page={{ paginator.num_pages }}" disabled="disabled">다음페이지</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ paginator.num_pages }}" disabled="disabled">다음페이지</a></li>    
            {% endif %}
        {% endif %}
    </ul>
</div>

StockAdmin2/templates/components/static.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static "bootstrap-4.0.0-beta.2-dist/css/bootstrap.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "jquery-ui-1.12.1/jquery-ui.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "tablesorter/themes/blue/style.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "font-awesome-4.7.0/css/font-awesome.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "css/common.css" %}">
    
<script src="{% static "jquery/jquery-3.2.1.min.js" %}"></script>
<script src="{% static "bootstrap-4.0.0-beta.2-dist/js/bootstrap.bundle.min.js" %}"></script>
<script src="{% static "jquery-ui-1.12.1/jquery-ui.min.js" %}"></script>
<script src="{% static "tablesorter/jquery.tablesorter.min.js" %}"></script>
<script src="{% static "tablesorter/addons/pager/jquery.tablesorter.pager.js" %}"></script>
<script src="{% static "js/common.js" %}"></script>
<script src="{% static "js/grid-table.js" %}"></script>