StockAdmin2/StockAdmin2/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeTemplateView

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('core/', include('core.urls', namespace='core')),
    path('product/', include('product.urls', namespace='product')),
    path('buy/', include('buy.urls', namespace='buy')),
]

StockAdmin2/buy/urls.py
from django.urls import path

from .views import *


app_name = 'buy'
urlpatterns = [
    path('', BuyListView.as_view(), name='buy-list'),
    path('cart/', BuyItemCartFormView.as_view(), name='buy-cart'),
    path('<slug:slug>/', BuyDetailView.as_view(), name='buy-detail'),
    path('update/<slug:slug>/', BuyUpdateView.as_view(), name='buy-update'),
    path('delete/<slug:slug>/', BuyDeleteView.as_view(), name='buy-delete'),
    path('confirm/<slug:slug>/', BuyConfirmView.as_view(), name='buy-confirm'),

    path('stockrecord/stocking/', StockRecordStockingView.as_view(), name='stock-stocking'),
    path('stockrecord/stocked/', stockrecord_stocked_view, name='stock-stocked'),
    path('stockrecord/agg/<slug:type>/', StockRecordAggregateView.as_view(), name='stock-agg'),
    path('buyitem/agg/<slug:type>/', BuyItemAggregateView.as_view(), name='buy-agg'),
    path('buyitem/update-set/', buyitem_update_view, name='buyitem-update-set'),
]

StockAdmin2/buy/forms.py
from django.utils import timezone
from django import forms
from django.forms import inlineformset_factory, modelformset_factory, modelform_factory

from .models import Buy, BuyItem, StockRecord


class BuyForm(forms.ModelForm):

    class Meta:
        model = Buy
        fields = 'commiter',

search_placeholder = '검색어 입력, 이미 입력된 품목은 뜨지 않음'

class BuyItemForm(forms.ModelForm):
    selected = forms.BooleanField(initial=False, required=False)
    buyinfo_name = forms.CharField(
        required=False, widget=forms.widgets.TextInput(attrs={'placeholder': search_placeholder})
    )
    class Meta:
        model = BuyItem
        fields = 'buy', 'buyinfo', 'amount', 'comment', 
        widgets = {
            'buyinfo': forms.widgets.HiddenInput()
        }

BuyItemFormSet = modelformset_factory(BuyItem,
    fields = ['isend'],
    extra=0,
)


class DateForm(forms.Form):
    date = forms.DateField(label='구매일자', initial=timezone.now(), required=False)


BuyItemInlineFormSet = inlineformset_factory(Buy, BuyItem, BuyItemForm,
    extra=1,
    can_delete=True,
    can_order=True,
)



BuyItemCartFormSet = modelformset_factory(BuyItem, BuyItemForm,
    extra = 1,
    can_delete = True,
)


class StockRecordForm(forms.ModelForm):
    end = forms.BooleanField(initial=False, required=False)

    class Meta:
        model = StockRecord
        fields = 'buyitem', 'date', 'amount',
        widgets = {
            'buyitem': forms.widgets.HiddenInput()
        }


StockRecordFormSet = modelformset_factory(StockRecord, StockRecordForm,
    extra=0,
    can_delete=True
)

StockAdmin2/core/filter/forms.py
from django import forms
from .settings import START_DATE_INI, END_DATE_INI


class DateFilterForm(forms.Form):
    start_date = forms.DateField(initial=START_DATE_INI)
    end_date = forms.DateField(initial=END_DATE_INI)


class SearchFilterForm(forms.Form):
    search = forms.CharField(label='검색어', required=False)


class MixedFililter(DateFilterForm):
    search = forms.CharField(label='검색어', required=False)

StockAdmin2/buy/views.py
from pprint import pprint

from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import *

from .models import Buy, BuyItem, StockRecord
from .forms import BuyForm, BuyItemInlineFormSet, BuyItemFormSet, BuyItemCartFormSet, DateForm, StockRecordFormSet
from .services import buyitem_formset_operation, rollback_to_cart, stockrecord_formset_operation
from core.filter import QueryFilter



class BuyListView(ListView):
    model = Buy



class BuyDetailView(DetailView):
    model = Buy
    fields = 'commiter',

    def get_context_data(self, **kwargs):
        context = super(BuyDetailView, self).get_context_data(**kwargs)
        context['form'] = BuyForm()
        return context



class BuyUpdateView(UpdateView):
    model = Buy
    fields = 'date', 'commiter',
    success_url = '.'

    def get_context_data(self, **kwargs):
        context = super(BuyUpdateView, self).get_context_data(**kwargs)
        formset = BuyItemInlineFormSet(self.request.POST or None, instance=self.get_object())
        context['formset'] = formset
        return context

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        if formset.is_valid():
            formset.save()
            if rollback_to_cart(formset):
                return HttpResponseRedirect(reverse('buy:buy-cart'))
        return super(BuyUpdateView, self).form_valid(form)



class BuyConfirmView(UpdateView):
    model = Buy
    fields = 'commiter',



class BuyDeleteView(DeleteView):
    model = Buy
    success_url = reverse_lazy('buy:buy-list')



class BuyItemCartFormView(FormView):
    form_class = DateForm
    template_name = 'buy/buyitem_cart.html'
    success_url = reverse_lazy('buy:buy-cart')

    def get_context_data(self, **kwargs):
        context = super(BuyItemCartFormView, self).get_context_data(**kwargs)
        qs = BuyItem.objects.filter(buy__isnull=True)
        context['formset'] = BuyItemCartFormSet(self.request.POST or None, queryset=qs)
        return context

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        if formset.is_valid():
            formset.save()
            buyitem_formset_operation(formset, form.cleaned_data['date'])
        return super(BuyItemCartFormView, self).form_valid(form)



class BuyItemAggregateView(ListView):
    model = BuyItem
    template_name = 'buy/buyitem_agg.html'

    def get_context_data(self, **kwargs):
        context = super(BuyItemAggregateView, self).get_context_data(**kwargs)
        agg_type = self.kwargs.get('type')
        qs = self.get_queryset().filter(buy__isnull=False, buy__commiter__isnull=False)
        qf = QueryFilter(self.request, queryset=qs)
        qf.set_filter_form_to_context(context)
        qs = qf.filter_by_all()
        annoset, total_buy_price = qs.group_by_fk(agg_type)
        context['object_list'] = annoset
        context['total_buy_price'] = total_buy_price
        return context



class StockRecordAggregateView(ListView):
    model = StockRecord
    template_name = 'buy/stocked_agg.html'

    def get_context_data(self, **kwargs):
        context = super(StockRecordAggregateView, self).get_context_data(**kwargs)
        agg_type = self.kwargs.get('type')
        qs = self.get_queryset()
        qf = QueryFilter(self.request, queryset=qs, app_name='StockRecord-stocked')
        qf.set_filter_form_to_context(context)
        # print(qs)
        qs = qf.filter_by_all()
        annoset, total_stocked_price = qs.group_by_fk(agg_type)
        context['object_list'] = annoset
        context['total_stocked_price'] = total_stocked_price
        return context



class StockRecordStockingView(FormView):
    form_class = DateForm
    success_url = '.'
    template_name = 'buy/stocking_form.html'

    def get_context_data(self, **kwargs):
        context = super(StockRecordStockingView, self).get_context_data(**kwargs)
        if self.request.method == "POST":
            context['formset'] = StockRecordFormSet(self.request.POST or None)
        else:
            qs = StockRecord.objects.filter(
                buyitem__buy__commiter__isnull=False,
                amount=0,
                buyitem__isend=False
            )
            qf = QueryFilter(self.request, app_name='StockRecord-stocking', queryset=qs)
            qf.set_filter_form_to_context(context)
            qs = qf.filter_by_all()
            context['formset'] = StockRecordFormSet(queryset=qs)
        return context

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        stock_date = form.cleaned_data['date']
        stockrecord_formset_operation(formset, stock_date)
        return super(StockRecordStockingView, self).form_valid(form)



def stockrecord_stocked_view(request):
    context = {}
    if request.method == "POST":
        formset = StockRecordFormSet(request.POST or None)
        stockrecord_formset_operation(formset)
        if formset.is_valid(): # 뒤에 호출하여야 DELETE가 먹힘
            formset.save()
        return redirect('.')
    else:
        qs = StockRecord.objects.filter(amount__gt=0)
        qf = QueryFilter(request, queryset=qs, app_name='StockRecord-stocked')
        qf.set_filter_form_to_context(context)
        qs = qf.filter_by_all()
        context['formset'] = StockRecordFormSet(queryset=qs)
        return render(request, 'buy/stocked_form.html', context)


def buyitem_update_view(request):
    context = {}
    if request.method == "POST":
        formset = BuyItemFormSet(request.POST or None)
        if formset.is_valid():
            formset.save()
            return redirect(request.META['HTTP_REFERER'])
        return redirect('.')
    else:
        qs = BuyItem.objects.filter(isend=True)
        qf = QueryFilter(request, queryset=qs)
        qf.set_filter_form_to_context(context)
        qs = qf.filter_by_all()
        context['formset'] = BuyItemFormSet(queryset=qs)
        return render(request, 'buy/buyitem_form.html', context)

StockAdmin2/core/filter/views.py
from django.db.models import Q

from .smart_filter import filter_searches
from .forms import DateFilterForm, SearchFilterForm
from .settings import LOOKUP_CONTEXTS



class QueryFilter(object):
    form_classes = {
        'date': DateFilterForm,
        'search': SearchFilterForm
    }
    date_form_name = 'date_filter_form'
    search_form_name = 'search_filter_form'

    def __init__(self, request, queryset=None, app_name=None):
        self.request = request
        self.queryset = queryset
        self.app_name = app_name

    def set_filter_form_to_context(self, context, date_form_name=None, search_form_name=None):
        context[date_form_name or self.date_form_name] = self.get_date_filter_form()
        context[search_form_name or self.search_form_name] = self.get_search_filter_form()
        return self

    def get_date_filter_form(self):
        Form = self.form_classes['date']
        return Form(self.request.GET or None)

    def get_search_filter_form(self):
        Form = self.form_classes['search']
        search_form = Form(self.request.GET or None)

        # if search_form.is_valid():
        #     search = search_form.cleaned_data.get('search')
            # self.request.session['search'] = search
        # else:
            # session_search = self.request.session.get('search')
            # if session_search:
            #     search_form.fields['search'].initial = session_search
        return search_form

    def filter_by_date(self, date_field=None, queryset=None, inplace=True):
        date_form = self.get_date_filter_form()
        qs = queryset or self.queryset
        if date_field is None:
            lookup = LOOKUP_CONTEXTS.get(self.app_name)
            if lookup:
                date_fields = lookup.get('date_range')
                if date_fields:
                    date_field = date_fields[0]

        if not qs or not date_field:
            return qs

        if date_form.is_valid():
            start_date = date_form.cleaned_data.get('start_date')
            end_date = date_form.cleaned_data.get('end_date')
        else:
            start_date = date_form.fields['start_date'].initial
            end_date = date_form.fields['end_date'].initial

        date_q = Q(**{'{}__range'.format(date_field): [start_date, end_date]})
        ret = qs.filter(date_q)
        if inplace:
            self.queryset = ret
        return ret

    def filter_by_search(self, app_name=None, queryset=None, inplace=True):
        search_form = self.get_search_filter_form()
        qs = queryset or self.queryset

        if not qs:
            return qs

        if search_form.is_valid():
            searches = search_form.cleaned_data.get('search')
            qs = filter_searches(qs, searches, app_name or self.app_name)

        if inplace:
            self.queryset = qs
        return qs

    def filter_by_all(self, **kwargs):
        self.filter_by_date(inplace=True, **kwargs)
        self.filter_by_search(inplace=True, **kwargs)
        return self.queryset

StockAdmin2/buy/templates/buy/components/buy_confirm_modal.html
<!-- Button trigger modal -->

<button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#btn-buy-confirm">
  발주승인
</button>

<div class="modal fade" id="btn-buy-confirm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">승인확인</h5>
      </div>
      <div class="modal-body text-center">
        {{ object.buyitem_set.count }}건 을 승인하시겠습니까?
      </div>
      <div class="modal-footer">
        <form method="post" action="{% url 'buy:buy-confirm' object.slug %}">
          {% csrf_token %}
          승인자:{{ form.commiter }}
          <button type="submit" class="btn btn-success btn-sm">승인</button>
        </form>
      </div>
    </div>
  </div>
</div>

StockAdmin2/buy/templates/buy/components/buy_nav.html
{% url 'buy:buy-agg' 'Market' as market_url %}
{% url 'buy:buy-agg' 'Product' as product_url %}
{% url 'buy:buy-agg' 'BuyInfo' as buyinfo_url %}
{% url 'buy:buy-agg' 'BuyItem' as buyitem_url %}
<ul class="nav nav-tabs nav-fill">
  <li class="nav-item">
    <a class="nav-link {% if request.path == buyitem_url %}active{% endif %} " href="{{ buyitem_url }}?{{ request.GET.urlencode }}" >개별내역</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if request.path == product_url %}active{% endif %} " href="{{ product_url }}?{{ request.GET.urlencode }}">제품별집계</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if request.path == buyinfo_url %}active{% endif %} " href="{{ buyinfo_url }}?{{ request.GET.urlencode }}">제품(구매정보)별집계</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if request.path == market_url %}active{% endif %} " href="{{ market_url }}?{{ request.GET.urlencode }}">거래처별집계</a>
  </li>
</ul>
<script>
$(function(){
  redirectFormActionOnClick('#filter-form', '[href={{ request.path }}]', "{{ request.path }}")
})
</script>

StockAdmin2/buy/templates/buy/components/filter_form.html
{% load widget_tweaks %}

    {# <div class="form-group"> #}
        조회:        
    {# </div> #}
    {# <div class="form-group"> #}
        {% render_field date_filter_form.start_date class="form-control-sm datepicker datepicker-start" readonly="true" tabindex=-1 %}~
    {# </div> #}
    {# <div class="form-group mr-2"> #}
        {% render_field date_filter_form.end_date class="form-control-sm datepicker datepicker-end" readonly="true" tabindex=-1 %}
    {# </div> #}
    {# <div class="form-group"> #}
        {% render_field search_filter_form.search class="form-control-sm" placeholder="검색어" %}
        <button class="btn btn-info btn-sm" type="submit" tabindex="-1" hidden>조회</button>
    {# </div> #}

StockAdmin2/buy/templates/buy/components/stock_nav.html
{% url 'buy:stock-agg' 'Market' as market_url %}
{% url 'buy:stock-agg' 'Product' as product_url %}
{% url 'buy:stock-agg' 'BuyInfo' as buyinfo_url %}
{% url 'buy:stock-agg' 'StockRecord' as stockrecord_url %}
<ul class="nav nav-tabs nav-fill">
  <li class="nav-item">
    <a class="nav-link {% if request.path == stockrecord_url %}active{% endif %} " href="{{ stockrecord_url }}?{{ request.GET.urlencode }}" >입고내역</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if request.path == product_url %}active{% endif %} " href="{{ product_url }}?{{ request.GET.urlencode }}">제품별집계</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if request.path == buyinfo_url %}active{% endif %} " href="{{ buyinfo_url }}?{{ request.GET.urlencode }}">제품(구매정보)별집계</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if request.path == market_url %}active{% endif %} " href="{{ market_url }}?{{ request.GET.urlencode }}">거래처별집계</a>
  </li>
</ul>
<script>
$(function(){
  redirectFormActionOnClick('#filter-form', '[href={{ request.path }}]', "{{ request.path }}")
})
</script>