StockAdmin2/StockAdmin2/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeTemplateView

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('core/', include('core.urls', namespace='core')),
    path('product/', include('product.urls', namespace='product')),
    path('buy/', include('buy.urls', namespace='buy')),
]

StockAdmin2/buy/urls.py
from django.urls import path

from .views import *


app_name = 'buy'
urlpatterns = [
    path('', BuyListView.as_view(), name='buy-list'),
    path('cart/', BuyItemCartFormView.as_view(), name='buy-cart'),
    path('<slug:slug>/', BuyDetailView.as_view(), name='buy-detail'),
    path('update/<slug:slug>/', BuyUpdateView.as_view(), name='buy-update'),
    path('delete/<slug:slug>/', BuyDeleteView.as_view(), name='buy-delete'),
    path('confirm/<slug:slug>/', BuyConfirmView.as_view(), name='buy-confirm'),

    path('stockrecord/stocking/', StockRecordStockingView.as_view(), name='stock-stocking'),
    path('stockrecord/stocked/', stockrecord_stocked_view, name='stock-stocked'),
    path('stockrecord/agg/<slug:type>/', StockRecordAggregateView.as_view(), name='stock-agg'),
    path('buyitem/agg/<slug:type>/', BuyItemAggregateView.as_view(), name='buy-agg'),
    path('buyitem/update-set/', buyitem_update_view, name='buyitem-update-set'),
]

StockAdmin2/buy/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import *
from django.urls import reverse
from django.utils import timezone

from .managers import StockRecordManager, BuyItemManager

from utils.shortcuts import sequence_date_slugify



class Buy(models.Model):
    slug = models.SlugField('구매번호', unique=True, blank=True, editable=False)
    commiter = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL)
    date = models.DateField('구매일자', blank=True, default=timezone.now)
    iscart = models.BooleanField('카트인지', blank=True, default=False)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = '구매요청서'
        verbose_name_plural = '구매요청서'
        ordering = '-created', 

    def __str__(self):
        return self.slug

    def save(self, **kwargs):
        if not self.slug:
            self.slug = sequence_date_slugify(self, 'date')
        return super(Buy, self).save(**kwargs)

    def get_absolute_url(self):
        return reverse('buy:buy-detail', args=(self.slug,))

    @property
    def description(self):
        itemset = self.buyitem_set.all()
        if itemset.exists():
            fistitem = str(itemset.first().buyinfo)
            count = itemset.count()
            return "{} 등 {}건".format(fistitem, count)
        return "내역없음"

    def get_complete_rate(self):
        total_buyitem_count = self.buyitem_set.count()
        if total_buyitem_count > 0:
            annoset = self.buyitem_set.annotate(stocked_amount_sum=Sum('stockrecord__amount'))
            completed_set = annoset.filter(Q(stocked_amount_sum=F('amount'))|Q(isend=True) )
            return completed_set.count() / total_buyitem_count
        return 0

    def has_stockset(self):
        return StockRecord.objects.filter(amount__gt=0, buyitem__buy=self).exists()

    def get_total_price_sum(self):
        annoset, total_price = self.buyitem_set.all().group_by_fk(only_valid=False)
        return total_price


class BuyItem(models.Model):
    buy = models.ForeignKey(Buy, null=True, blank=True, on_delete=models.CASCADE)
    buyinfo = models.ForeignKey('product.BuyInfo', on_delete=models.PROTECT)
    amount = models.IntegerField('구매수량')
    comment = models.CharField('비고', max_length=50, blank=True)
    isend = models.BooleanField('구매종결', default=False)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = BuyItemManager()

    class Meta:
        verbose_name = '구매품목'
        verbose_name_plural = '구매품목'
        unique_together = 'buy', 'buyinfo',

    def __init__(self, *args, **kwargs):
        super(BuyItem, self).__init__(*args, **kwargs)

    def __str__(self):
        return str(self.buyinfo)

    def save(self, **kwargs):
        super(BuyItem, self).save(**kwargs)
        self.reload_zero_stockrecord()          

    def get_stocked_sum(self):
        aggset = self.stockrecord_set.aggregate(stocked=Sum('amount'))
        return aggset['stocked'] or 0

    def get_incompleted_stock(self):
        return self.amount - self.get_stocked_sum()

    def get_incompleted_stock_by_pkg(self):
        incompleted_stock = self.get_incompleted_stock()
        pkg_amount = self.buyinfo.product.pkg_amount or 1
        return incompleted_stock//pkg_amount

    @property
    def stocked_percent(self):
        return self.get_stocked_sum()*100/self.amount

    @property
    def ended_percent(self):
        if self.isend:
            return 100 - self.stocked_percent
        return 0

    def get_stock_status(self):
        if self.isend == True:
            return '종결'
        elif self.get_incompleted_stock() == 0:
            return '완료'
        else:
            return '입고중'

    def get_buy_price(self):
        price = self.buyinfo.price or 0
        return self.amount * price

    @property
    def iscompleted(self):
        return self.get_stock_status() in ['완료', '종결']

    def reload_zero_stockrecord(self):
        zeroset = self.stockrecord_set.filter(amount=0)

        if self.iscompleted:
            if zeroset.exists():
                zeroset.delete()
        else:
            if zeroset.exists():
                if zeroset.count() > 1:
                    zeroset.delete()
                    self.stockrecord_set.create()
            else:
                self.stockrecord_set.create()



class StockRecord(models.Model):
    buyitem = models.ForeignKey(BuyItem, on_delete=models.CASCADE)
    date = models.DateField('입고일자', blank=True, null=True)
    amount = models.IntegerField('입고수량', default=0)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = StockRecordManager()

    class Meta:
        verbose_name_plural = '입고기록'
        verbose_name = '입고기록'
        ordering = '-buyitem__created',

    def __init__(self, *args, **kwargs):
        super(StockRecord, self).__init__(*args, **kwargs)
        self.old_amount  = self.amount
        
    def __str__(self):
        return str(self.buyitem)

    def save(self, **kwargs):
        super(StockRecord, self).save(**kwargs)
        self.buyitem.reload_zero_stockrecord()

    def delete(self):
        buyitem = self.buyitem
        super(StockRecord, self).delete()
        buyitem.reload_zero_stockrecord()

    def clean(self):
        stockrecord_set = self.buyitem.stockrecord_set
        if self.id:
            stocked_amount = self.buyitem.get_stocked_sum()
            new_amount = stocked_amount - self.old_amount + self.amount
            if new_amount > self.buyitem.amount:
                raise ValidationError('입고수량이 구매수량을 초과 합니다')

StockAdmin2/buy/forms.py
from django.utils import timezone
from django import forms
from django.forms import inlineformset_factory, modelformset_factory, modelform_factory

from .models import Buy, BuyItem, StockRecord


class BuyForm(forms.ModelForm):

    class Meta:
        model = Buy
        fields = 'commiter',

search_placeholder = '검색어 입력, 이미 입력된 품목은 뜨지 않음'

class BuyItemForm(forms.ModelForm):
    selected = forms.BooleanField(initial=False, required=False)
    buyinfo_name = forms.CharField(
        required=False, widget=forms.widgets.TextInput(attrs={'placeholder': search_placeholder})
    )
    class Meta:
        model = BuyItem
        fields = 'buy', 'buyinfo', 'amount', 'comment', 
        widgets = {
            'buyinfo': forms.widgets.HiddenInput()
        }

BuyItemFormSet = modelformset_factory(BuyItem,
    fields = ['isend'],
    extra=0,
)


class DateForm(forms.Form):
    date = forms.DateField(label='구매일자', initial=timezone.now(), required=False)


BuyItemInlineFormSet = inlineformset_factory(Buy, BuyItem, BuyItemForm,
    extra=1,
    can_delete=True,
    can_order=True,
)



BuyItemCartFormSet = modelformset_factory(BuyItem, BuyItemForm,
    extra = 1,
    can_delete = True,
)


class StockRecordForm(forms.ModelForm):
    end = forms.BooleanField(initial=False, required=False)

    class Meta:
        model = StockRecord
        fields = 'buyitem', 'date', 'amount',
        widgets = {
            'buyitem': forms.widgets.HiddenInput()
        }


StockRecordFormSet = modelformset_factory(StockRecord, StockRecordForm,
    extra=0,
    can_delete=True
)

StockAdmin2/buy/views.py
from pprint import pprint

from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.views.generic import *

from .models import Buy, BuyItem, StockRecord
from .forms import BuyForm, BuyItemInlineFormSet, BuyItemFormSet, BuyItemCartFormSet, DateForm, StockRecordFormSet
from .services import buyitem_formset_operation, rollback_to_cart, stockrecord_formset_operation
from core.filter import QueryFilter



class BuyListView(ListView):
    model = Buy



class BuyDetailView(DetailView):
    model = Buy
    fields = 'commiter',

    def get_context_data(self, **kwargs):
        context = super(BuyDetailView, self).get_context_data(**kwargs)
        context['form'] = BuyForm()
        return context



class BuyUpdateView(UpdateView):
    model = Buy
    fields = 'date', 'commiter',
    success_url = '.'

    def get_context_data(self, **kwargs):
        context = super(BuyUpdateView, self).get_context_data(**kwargs)
        formset = BuyItemInlineFormSet(self.request.POST or None, instance=self.get_object())
        context['formset'] = formset
        return context

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        if formset.is_valid():
            formset.save()
            if rollback_to_cart(formset):
                return HttpResponseRedirect(reverse('buy:buy-cart'))
        return super(BuyUpdateView, self).form_valid(form)



class BuyConfirmView(UpdateView):
    model = Buy
    fields = 'commiter',



class BuyDeleteView(DeleteView):
    model = Buy
    success_url = reverse_lazy('buy:buy-list')



class BuyItemCartFormView(FormView):
    form_class = DateForm
    template_name = 'buy/buyitem_cart.html'
    success_url = reverse_lazy('buy:buy-cart')

    def get_context_data(self, **kwargs):
        context = super(BuyItemCartFormView, self).get_context_data(**kwargs)
        qs = BuyItem.objects.filter(buy__isnull=True)
        context['formset'] = BuyItemCartFormSet(self.request.POST or None, queryset=qs)
        return context

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        if formset.is_valid():
            formset.save()
            buyitem_formset_operation(formset, form.cleaned_data['date'])
        return super(BuyItemCartFormView, self).form_valid(form)



class BuyItemAggregateView(ListView):
    model = BuyItem
    template_name = 'buy/buyitem_agg.html'

    def get_context_data(self, **kwargs):
        context = super(BuyItemAggregateView, self).get_context_data(**kwargs)
        agg_type = self.kwargs.get('type')
        qs = self.get_queryset().filter(buy__isnull=False, buy__commiter__isnull=False)
        qf = QueryFilter(self.request, queryset=qs)
        qf.set_filter_form_to_context(context)
        qs = qf.filter_by_all()
        annoset, total_buy_price = qs.group_by_fk(agg_type)
        context['object_list'] = annoset
        context['total_buy_price'] = total_buy_price
        return context



class StockRecordAggregateView(ListView):
    model = StockRecord
    template_name = 'buy/stocked_agg.html'

    def get_context_data(self, **kwargs):
        context = super(StockRecordAggregateView, self).get_context_data(**kwargs)
        agg_type = self.kwargs.get('type')
        qs = self.get_queryset()
        qf = QueryFilter(self.request, queryset=qs, app_name='StockRecord-stocked')
        qf.set_filter_form_to_context(context)
        # print(qs)
        qs = qf.filter_by_all()
        annoset, total_stocked_price = qs.group_by_fk(agg_type)
        context['object_list'] = annoset
        context['total_stocked_price'] = total_stocked_price
        return context



class StockRecordStockingView(FormView):
    form_class = DateForm
    success_url = '.'
    template_name = 'buy/stocking_form.html'

    def get_context_data(self, **kwargs):
        context = super(StockRecordStockingView, self).get_context_data(**kwargs)
        if self.request.method == "POST":
            context['formset'] = StockRecordFormSet(self.request.POST or None)
        else:
            qs = StockRecord.objects.filter(
                buyitem__buy__commiter__isnull=False,
                amount=0,
                buyitem__isend=False
            )
            qf = QueryFilter(self.request, app_name='StockRecord-stocking', queryset=qs)
            qf.set_filter_form_to_context(context)
            qs = qf.filter_by_all()
            context['formset'] = StockRecordFormSet(queryset=qs)
        return context

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        stock_date = form.cleaned_data['date']
        stockrecord_formset_operation(formset, stock_date)
        return super(StockRecordStockingView, self).form_valid(form)



def stockrecord_stocked_view(request):
    context = {}
    if request.method == "POST":
        formset = StockRecordFormSet(request.POST or None)
        stockrecord_formset_operation(formset)
        if formset.is_valid(): # 뒤에 호출하여야 DELETE가 먹힘
            formset.save()
        return redirect('.')
    else:
        qs = StockRecord.objects.filter(amount__gt=0)
        qf = QueryFilter(request, queryset=qs, app_name='StockRecord-stocked')
        qf.set_filter_form_to_context(context)
        qs = qf.filter_by_all()
        context['formset'] = StockRecordFormSet(queryset=qs)
        return render(request, 'buy/stocked_form.html', context)


def buyitem_update_view(request):
    context = {}
    if request.method == "POST":
        formset = BuyItemFormSet(request.POST or None)
        if formset.is_valid():
            formset.save()
            return redirect(request.META['HTTP_REFERER'])
        return redirect('.')
    else:
        qs = BuyItem.objects.filter(isend=True)
        qf = QueryFilter(request, queryset=qs)
        qf.set_filter_form_to_context(context)
        qs = qf.filter_by_all()
        context['formset'] = BuyItemFormSet(queryset=qs)
        return render(request, 'buy/buyitem_form.html', context)

StockAdmin2/buy/templates/buy/buy_base.html
{% extends "base.html" %}

{% block navbar %}
    
{% endblock navbar %}

{% block extra_style %}
    
{% endblock extra_style %}

{% block content %}
<div class="container">
    <div class="col-12 my-3">
    {% block buy_header %}{% endblock buy_header %}
    </div>
    <div class="col-12">
    {% block buy_content %}{% endblock buy_content %}
    </div>
    <div style="min-height: 200px;">
        
    </div>
</div>

{% block extra_scrip %}
<script type="text/javascript">
$(function(){

    $('input[name$=amount]').change(function(event){
        tr = $(this).parents('tr')
        var chk_delelete = tr.find('input[name*=DELETE]')
        var checked = $(this).val() == 0 || $(this).val() === ''
        chk_delelete.prop('checked', checked)
    })
    
    checkSync('.check-master', 'input[name*=selected]')

})
</script>
{% endblock extra_scrip %}
{% endblock content %}

StockAdmin2/buy/templates/buy/buy_detail.html
{% extends "buy/buy_base.html" %}
{% load humanize %}

{% block buy_header %}
<div class="col-12">
<h4>구매요청서 상세</h4>
</div>
{% endblock buy_header %}

{% block buy_content %}
<div class="col-12">
        <div class="row px-3">
        <div class="col-8">
            거래처: {{ object.buyitem_set.first.buyinfo.market }}</br>
            구매번호: {{ object.slug }}<br>
            구매건수: {{ object.buyitem_set.all|length }}건 <br>
            총구매액: {{ object.get_total_price_sum|intcomma }}     
        </div>
        <div class="col-4">
            <table class="table table-bordered table-sm h-100 text-center">
                <thead>
                    <tr>
                        <td>담당자</td>
                        <td>발주승인</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="align-middle">{{ request.user }}</td>
                        <td class="align-middle"> {{ object.commiter|default:"" }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>   
</div>
<div class="text-right">
</div>
    <table class="table-bordered tablesorter tablesorter-sortable">
        <thead class="thead-default text-center">
            <tr>
                <th>연번</th>
                <th>판매사</th>
                <th>구매항목</th>
                <th>구매수량</th>
                <th>현재입고량</th>
                <th>입고율</th>
                <th>비고</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object.buyitem_set.all %}
            <tr>
                <td class="text-center">{{ forloop.counter }}</td>
                <td>{{ item.buyinfo.product.company }} </td>
                <td>{{ item.buyinfo.product }}</td>
                <td class="text-right">{{ item.amount|intcomma }} {{ item.buyinfo.product.std_unit }}</td>
                <td class="text-right">{{ item.get_stocked_sum }}</td>
                <td>
                    <div class="progress">
                        <div class="progress-bar bg-success" style="width:{{ item.stocked_percent }}%;"></div>
                        {% if item.isend %}
                        <div class="progress-bar bg-danger" style="width:{{ item.ended_percent }}%"></div>
                        {% endif %}
                    </div>
                </td>
                <td>{{ item.comment }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="col-12 text-right">
        <a class="btn btn-info btn-sm" href="{% url 'buy:buy-list' %}">목록으로</a>
        {% if object.commiter %}
            <button class="btn btn-secondary btn-sm" onclick="printArea('.print-area')">
                출력<i class="fa fa-print" aria-hidden="true"></i>
            </button>
            {% if object.has_stockset %}
                <button class="btn btn-danger btn-sm disabled">구매요청서 삭제</button>
            {% else %}
                {% url 'buy:buy-delete' object.slug as delete_url %}
                {% include "components/delete_confirm_button.html" with button_name="구매요청서 삭제" modal_id="modal-buy-delete" action=delete_url %}
            {% endif %}
        {% else %}
        <a class="btn btn-warning btn-sm" href="{% url 'buy:buy-update' object.slug %}">구매내역 수정</a>
            {% if user.is_staff %}
            {% include "buy/components/buy_confirm_modal.html" %}
            {% endif %}
        {% endif %}
    </div>

    <div class="print-area">
        {% include "buy/components/print/buy_detail_print.html" %}
    </div>

{% endblock buy_content %}

StockAdmin2/buy/templates/buy/buyitem_agg.html
{% extends "buy/buy_base.html" %}
{% load humanize %}
{% load widget_tweaks %}


{% block extra_style %}
<style type="text/css">
    th {
        background-color: palegreen !important;
    }
</style>
{% endblock extra_style %}


{% block buy_header %}
<div class="col-12 mb-4">
    <h4>구매내역</h4>
    <form id="form-filter" class="form" method="get" action=".">
        <div class="form-group form-row">
        <div class="col-6">
            {% include "buy/components/filter_form.html" %}
        </div>

    </form>
</div>
<div class="col-12">
    <hr>
    {% include "buy/components/buy_nav.html" %}
</div>
{% endblock buy_header %}


{% block buy_content %}
{% url 'buy:buy-agg' 'Market' as market_url %}
{% url 'buy:buy-agg' 'Product' as product_url %}
{% url 'buy:buy-agg' 'BuyInfo' as buyinfo_url %}
{% url 'buy:buy-agg' 'BuyItem' as buyitem_url %}

<div class="col-12">

{% if request.path == buyitem_url %}
    <table class="tablesorter tablesorter-sortable table-bordered">
        <thead>
            <tr>
                <th>구매번호</th>
                <th>거래처</th>
                <th>판매사</th>
                <th>제품명</th>
                <th>입고상태</th>
                <th>구매단가</th>
                <th>구매수량</th>
                <th>입고된수량</th>
                <th>입고된가격</th>
                <th>총구매액</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <td class="text-center">{{ object.buy.slug }}</td>
                <td class="text-center">{{ object.buyinfo.market }}</td>
                <td class="text-center">{{ object.buyinfo.product.company }}</td>
                <td>{{ object.buyinfo.product.name }}</td>
                <td class="text-center">{{ object.stock_status }}</td>
                <td class="text-right">{{ object.buyinfo.price|intcomma }}</td>
                <td class="text-right">{{ object.amount|intcomma }}</td>
                <td class="text-right">{{ object.stocked_amount_sum|default:0|intcomma }}</td>
                <td class="text-right">{{ object.stocked_price_sum|intcomma }}</td>
                <td class="text-right">{{ object.buy_price_sum|intcomma }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="text-right">
        <span><b>구매금액 종합: {{ total_buy_price|intcomma }}</b></span>
    </div>
{% elif request.path == product_url %}

<table class="tablesorter tablesorter-sortable table-bordered">
    <thead>
        <tr>
            <th>제품코드</th>
            <th>제품명</th>
            <th>거래처</th>
            <th>제품단가</th>
            <th>총구매수량</th>
            <th>총구매가</th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
        <tr>
            <td class="text-center">{{ object.product_code }}</td>
            <td>{{ object.product_name }}</td>
            <td>{{ object.market_name }}</td>
            <td class="text-right">{{ object.price|intcomma }}</td>
            <td class="text-right">{{ object.buy_amount_sum|intcomma }}</td>
            <td class="text-right">{{ object.buy_price_sum|intcomma }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div class="text-right">
    <span><b>구매금액 종합: {{ total_buy_price|intcomma }}</b></span>
</div>
{% elif request.path == buyinfo_url %}
<table class="tablesorter tablesorter-sortable table-bordered">
    <thead>
        <tr>
            <th>구매정보ID</th>
            <th>거래처</th>
            <th>제품명</th>
            <th>제품단가</th>
            <th>총구매수량</th>
            <th>총구매가</th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
        <tr>
            <td class="text-center">{{ object.buyinfo_slug }}</td>
            <td class="text-center">{{ object.market_name }}</td>
            <td>{{ object.product_name }}</td>
            <td class="text-center">{{ object.price|intcomma }}</td>
            <td class="text-right">{{ object.buy_amount_sum|intcomma }}</td>
            <td class="text-right">{{ object.buy_price_sum|intcomma }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div class="text-right">
    <span><b>구매금액 종합: {{ total_buy_price|intcomma }}</b></span>
</div>
{% elif request.path == market_url %}
<table class="tablesorter tablesorter-sortable table-bordered">
    <thead>
        <tr>
            <th>거래처</th>
            <th>구매건수</th>
            <th>구매품목건수</th>
            <th>총구매가격</th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
        <tr>
            <td class="text-center">{{ object.market_name }}</td>
            <td class="text-right">{{ object.buy_count|intcomma }}</td>
            <td class="text-right">{{ object.buyitem_count|intcomma }}</td>
            <td class="text-right">{{ object.buy_price_sum|intcomma }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div class="text-right">
    <span><b>구매금액 종합: {{ total_buy_price|intcomma }}</b></span>
</div>
{% endif %}
    
</div>

{% endblock buy_content %}

{% block extra_script %}
<script>
$(function(){
    
})
</script>
{% endblock extra_script %}

StockAdmin2/buy/templates/buy/stocking_form.html
{% extends "buy/buy_base.html" %}
{% load humanize %}
{% load widget_tweaks %}


{% block buy_header %}
<div class="col-12">
    <h4>입고잡기</h4>
<form id="form-filter" class="form" method="get" action=".">
    <div class="form-group form-row">
        <div class="col-6">
            {% include "buy/components/filter_form.html" %}
        </div>
        <div class="col-6 text-right">
            <a class="btn btn-secondary btn-sm" href="{% url 'buy:stock-agg' 'StockRecord' %}?{{ request.GET.urlencode }}">
                입고내역<i class="fa fa-search" aria-hidden="true"></i>
            </a>
            <a class="btn btn-secondary btn-sm" href="{% url 'buy:stock-stocked' %}?{{ request.GET.urlencode }}">
                입고수정<i class="fa fa-pencil-square-o fa-lg" aria-hidden="true"></i>
            </a>            
            <a class="btn btn-secondary btn-sm" href="{% url 'buy:buyitem-update-set' %}?{{ request.GET.urlencode }}">
                종결내역<i class="fa fa-battery-quarter" aria-hidden="true"></i>
            </a>            
        </div>
    </div>
</form>
</div>
{% endblock buy_header %}


{% block buy_content %}
<div class="col-12">
    <hr>
    <form method="post" action=".">
        {% csrf_token %}
        {{ formset.management_form }}
        <div class="form-group text-left">
            
            <label>입고일자지정:</label>
            {% render_field form.date class="form-control-sm datepicker" readonly="true" tabindex="-1" %}
        </div>
        <table class="table-bordered tablesorter tablesorter-sortable">
            <thead class="text-center thead-light">
                <tr>
                    <th>구매번호</th>
                    <th>거래처</th>
                    <th>판매사</th>
                    <th>항목</th>
                    <th>입고</th>
                    <th>미입고</th>
                    <th>입고됨</th>
                    <th>구매량</th>
                    <th>종결</th>
                </tr>
            </thead>
            <tbody>
                {% for form in formset %}
                    {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
                <tr>
                    <td class="text-center">{{ form.instance.buyitem.buy.slug }}</td>
                    <td class="text-center">{{ form.instance.buyitem.buyinfo.market }}</td>
                    <td>{{ form.instance.buyitem.buyinfo.product.company }}</td>
                    <td>{{ form.buyitem }}{{ form.instance.buyitem.buyinfo.product }}</td>
                    {% with amount_step=form.instance.buyitem.buyinfo.product.pkg_amount amount_rest=form.instance.buyitem.get_incompleted_stock %}
                    <td class="amount">{% render_field form.amount step=amount_step min=0 max=amount_rest %}</td>
                    {% endwith %}
                    <td class="text-right">
                        {{ form.instance.buyitem.get_incompleted_stock }}({{ form.instance.buyitem.get_incompleted_stock_by_pkg }})
                    </td>
                    <td class="text-right">{{ form.instance.buyitem.get_stocked_sum }}</td>
                    <td class="text-right">{{ form.instance.buyitem.amount }}</td>
                    <td class="text-center">{{ form.end|attr:"tabindex:-1" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="form-group text-right">
            <button type="submit" class="btn btn-success btn-sm">입고저장<i class="fa fa-floppy-o" aria-hidden="true"></i></button>
        </div>
    </form>
</div>
{% block extra_scrip %}
<script>
$(function(){

    
    $('input[name$=amount]').keyup(function(event){
        console.log(event)
    })

    $('input[name$=amount]').keydown(function(event){
        var kc = event.keyCode
        var step = parseInt($(this).attr('step'))
        var max = parseInt($(this).attr('max'))
        var cur = parseInt($(this).val()) || 0
        if (kc == 32) {
            $(this).val(max)
        }
        else if (kc == 37) {
            var amount = cur-step
            if (amount >= 0) {
                $(this).val(amount)
            }
            return false
        }else if (kc == 39) {
            console.log(cur)
            var amount = cur+step
            if (amount <= max) {
                $(this).val(amount)
            }
            return false
        }
        if ($(this).val() == "") {
            $(this).val(0)
        }
    })
})
</script>
{% endblock extra_scrip %}

{% endblock buy_content %}